Add sections for variance errors
bennycode/typescript-errors pull request #3
Opened 2023-04-25 04:21 UTC by Masa-Shin

2023-04-25 06:26 UTC, bennycode requested changes
Hey, happy to see you again! 🙂 Let's put the variable values of an error message into code blocks so it's visible that this part of the error message is based on your custom code.

2023-04-25 06:26 UTC, bennycode commented on errors/includes/TS2xxx/TS2636.md
> +> error TS2636: Type 'Func<super-T>' is not assignable to type 'Func<sub-T>' as implied by variance annotation. Type 'super-T' is not assignable to type 'sub-T'.
```suggestion
> error TS2636: Type '`Func<super-T>`' is not assignable to type '`Func<sub-T>`' as implied by variance annotation. Type '`super-T`' is not assignable to type '`sub-T`'.
```

2023-04-25 06:31 UTC, Masa-Shin commented
Thanks! Updated.

2023-04-25 11:03 UTC, merged

2023-04-26 23:27 UTC, bennycode commented
Cool! It's live on https://typescript.tv/errors/#TS2636 - Thank you very much! 👍👍